### ISSUE TITLE
Typo on volume names in docker-compose.yml prevents volumes from loading

### ISSUE THREAD

**Issue by edanzer** [gitpod-io/template-wordpress#1]
### Bug description

When clicking the Gitpod button for this repository, or when following the installation steps in the readme, I get the following error within the console inside of Gitpod: 

"ERROR: Named volume "database:/var/lib/mysql:rw" is used in service "db" but no declaration was found in the volumes section."

### Steps to reproduce

Click the Gitpod button for this repository, or follow the installation steps in the readme to clone the template to your own repo, and launch Gitpod from there. 

### Expected behavior

Expect that the Docker volumes for db and WordPress volumes to load fully for a fully working WordPress website. 

### Example repository

You can duplicate the issue from this repository. 

### Anything else?

I believe the issue is simply that the in the bottom of the docker-compose file, where volumes are specified, the wrong names are provided for the volumes. The db and wordpress services use named volumes ("db" and "src") respectively. 

If you replace this: 

```
volumes:
  db_data: {}
  wordpress_data: {}
```

with this: 

```
volumes:
  database: 
  src: 
```

then everything loads correctly. 

I'd be happy to submit a quick pull request with this fix if you like.

**Comment by edanzer** [comment]
You can test the proposed fix by clicking the Gitpod button from this branch: 
https://github.com/edanzer/template-wordpress/tree/bug/fixed-docker-volume-names

Again, happy to submit a pull request. It's a very minor change.

**Comment by pawlean** [comment]
> You can test the proposed fix by clicking the Gitpod button from this branch: https://github.com/edanzer/template-wordpress/tree/bug/fixed-docker-volume-names
> 
> Again, happy to submit a pull request. It's a very minor change.

Please do :)

**Comment by edanzer** [comment]
@pawlean Sorry for the delay! I've submitted a pull request. :)
